has = fn checks -> for {mod, opts} <- checks, Code.ensure_loaded?(mod), do: {mod, opts} end

%{
  configs: [
    %{
      name: "default",
      checks: %{
        extra:
          has.([
            {Credo.Check.Consistency.ExceptionNames, []},
            {Credo.Check.Consistency.LineEndings, []},
            {Credo.Check.Consistency.MultiAliasImportRequireUse, []},
            {Credo.Check.Consistency.ParameterPatternMatching, []},
            {Credo.Check.Consistency.SpaceAroundOperators, []},
            {Credo.Check.Consistency.SpaceInParentheses, []},
            {Credo.Check.Consistency.TabsOrSpaces, []},
            {Credo.Check.Design.AliasUsage, [priority: :low, if_nested_deeper_than: 3, if_called_more_often_than: 2]},
            {Credo.Check.Design.DeprecatedChecksConfig, []},
            {Credo.Check.Design.DuplicatedCode, []},
            {Credo.Check.Design.MissingCheckInConfig, []},
            {Credo.Check.Design.RedundantConfigComments, []},
            {Credo.Check.Design.SkipTestWithoutComment, []},
            {Credo.Check.Design.TagFIXME, [exit_status: 0]},
            {Credo.Check.Design.TagTODO, [exit_status: 0]},
            {Credo.Check.Readability.AliasOrder, []},
            {Credo.Check.Readability.BlockPipe, []},
            {Credo.Check.Readability.FunctionNames, []},
            {Credo.Check.Readability.ImplTrue, []},
            {Credo.Check.Readability.LargeNumbers, [only_greater_than: 99_999]},
            {Credo.Check.Readability.MaxLineLength, [priority: :low, max_length: 120]},
            {Credo.Check.Readability.ModuleAttributeNames, []},
            {Credo.Check.Readability.ModuleDoc, []},
            {Credo.Check.Readability.ModuleNames, []},
            {Credo.Check.Readability.MultiAlias, []},
            {Credo.Check.Readability.NestedFunctionCalls, [min_pipeline_length: 3]},
            {Credo.Check.Readability.OneArityFunctionInPipe, []},
            {Credo.Check.Readability.OnePipePerLine, []},
            {Credo.Check.Readability.ParenthesesInCondition, []},
            {Credo.Check.Readability.ParenthesesOnZeroArityDefs, []},
            {Credo.Check.Readability.PipeIntoAnonymousFunctions, []},
            {Credo.Check.Readability.PredicateFunctionNames, []},
            {Credo.Check.Readability.PreferImplicitTry, []},
            {Credo.Check.Readability.RedundantBlankLines, []},
            {Credo.Check.Readability.Semicolons, []},
            {Credo.Check.Readability.SeparateAliasRequire, []},
            {Credo.Check.Readability.SingleFunctionToBlockPipe, []},
            {Credo.Check.Readability.SinglePipe, []},
            {Credo.Check.Readability.SpaceAfterCommas, []},
            {Credo.Check.Readability.SpecParameterNames, []},
            {Credo.Check.Readability.StrictModuleLayout, []},
            {Credo.Check.Readability.StringSigils, []},
            {Credo.Check.Readability.TrailingBlankLine, []},
            {Credo.Check.Readability.TrailingWhiteSpace, []},
            {Credo.Check.Readability.UnnecessaryAliasExpansion, []},
            {Credo.Check.Readability.VariableNames, []},
            {Credo.Check.Readability.WithCustomTaggedTuple, []},
            {Credo.Check.Readability.WithSingleClause, []},
            {Credo.Check.Refactor.Apply, []},
            {Credo.Check.Refactor.CondStatements, []},
            {Credo.Check.Refactor.CyclomaticComplexity, []},
            {Credo.Check.Refactor.FilterCount, []},
            {Credo.Check.Refactor.FilterFilter, []},
            {Credo.Check.Refactor.FilterReject, []},
            {Credo.Check.Refactor.FunctionArity, []},
            {Credo.Check.Refactor.LongQuoteBlocks, []},
            {Credo.Check.Refactor.MapJoin, []},
            {Credo.Check.Refactor.MapMap, []},
            {Credo.Check.Refactor.MatchInCondition, []},
            {Credo.Check.Refactor.NegatedConditionsInUnless, []},
            {Credo.Check.Refactor.NegatedConditionsWithElse, []},
            {Credo.Check.Refactor.NegatedIsNil, []},
            {Credo.Check.Refactor.Nesting, []},
            {Credo.Check.Refactor.PassAsyncInTestCases, []},
            {Credo.Check.Refactor.PipeChainStart, []},
            {Credo.Check.Refactor.PreferDateTimeShift, []},
            {Credo.Check.Refactor.RedundantWithClauseResult, []},
            {Credo.Check.Refactor.RejectFilter, []},
            {Credo.Check.Refactor.RejectReject, []},
            {Credo.Check.Refactor.UnlessWithElse, []},
            {Credo.Check.Refactor.UtcNowTruncate, []},
            {Credo.Check.Refactor.WithClauses, []},
            {Credo.Check.Warning.ApplicationConfigInModuleAttribute, []},
            {Credo.Check.Warning.BoolOperationOnSameValues, []},
            {Credo.Check.Warning.Dbg, []},
            {Credo.Check.Warning.ExpensiveEmptyEnumCheck, []},
            {Credo.Check.Warning.ForbiddenFunction, []},
            {Credo.Check.Warning.ForbiddenModule, []},
            {Credo.Check.Warning.IExPry, []},
            {Credo.Check.Warning.IoInspect, []},
            {Credo.Check.Warning.MapGetUnsafePass, []},
            {Credo.Check.Warning.MissedMetadataKeyInLoggerConfig, []},
            {Credo.Check.Warning.MixEnv, []},
            {Credo.Check.Warning.OperationOnSameValues, []},
            {Credo.Check.Warning.OperationWithConstantResult, []},
            {Credo.Check.Warning.RaiseInsideRescue, []},
            {Credo.Check.Warning.SpecWithStruct, []},
            {Credo.Check.Warning.StructFieldAmount, []},
            {Credo.Check.Warning.UnsafeExec, []},
            {Credo.Check.Warning.UnsafeToAtom, []},
            {Credo.Check.Warning.UnusedEnumOperation, []},
            {Credo.Check.Warning.UnusedFileOperation, []},
            {Credo.Check.Warning.UnusedKeywordOperation, []},
            {Credo.Check.Warning.UnusedListOperation, []},
            {Credo.Check.Warning.UnusedMapOperation, []},
            {Credo.Check.Warning.UnusedOperation, []},
            {Credo.Check.Warning.UnusedPathOperation, []},
            {Credo.Check.Warning.UnusedRegexOperation, []},
            {Credo.Check.Warning.UnusedStringOperation, []},
            {Credo.Check.Warning.UnusedTupleOperation, []},
            {Credo.Check.Warning.WrongTestFilename, []}
          ])
      }
    }
  ]
}
